### ISSUE TITLE
Typo: altitudeMeters should be altitude

### ISSUE THREAD

**Issue by alan-leslie** [google-ar/codelab-geospatial#1]
In step 4 'Determine the positioning of the new Anchor' the altitude is calculated from:
val altitude = earth.cameraGeospatialPose.altitudeMeters - 1

I believe that that is a typo and should just be:
val altitude = earth.cameraGeospatialPose.altitude - 1

which is documented as
Returns the GeospatialPose's altitude in meters as elevation above the WGS84 ellipsoid .

**Comment by devbridie** [comment]
Thanks for that-- changes should be up either now or coming to you soon.
