### ISSUE TITLE
EunRotation does not exist in Unity

### ISSUE THREAD

**Issue by TimmyBest** [google-ar/codelab-geospatial#15]
The documentation states this:
![image (5)](https://user-images.githubusercontent.com/25765075/211043867-b8db2e28-36ad-40df-baf8-78d1362d4182.png)

But when in Unity:
![image (4)](https://user-images.githubusercontent.com/25765075/211043945-e0c730ec-bbe5-400f-9d32-bb4d7f912c6b.png)

Probably forgot to make it public..?😉

**Comment by devbridie** [comment]
Hi,
`EunRotation` is [new in 1.35.0](https://github.com/google-ar/arcore-unity-extensions/releases/tag/v1.35.0), so it may be that you're not up-to-date with the latest version of the SDK for Unity! I can see `EunRotation` here: https://github.com/google-ar/arcore-unity-extensions/blob/master/Runtime/Scripts/GeospatialPose.cs#L160

**Comment by TimmyBest** [comment]
Yep, the holy update! 🙏🏻
